project:
  type: website

website:
  title: "Statistics with GPT friend"
  navbar:
    left:
      - href: index.qmd
      - text: "Topics"
        menu: 
          - href: Topic1.qmd
            text: Mathematics and Statistics
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true