---
title: Summary
format: 
  html: 
    page-layout: full
listing: 
  - id: foundations
    contents: "posts/foundations/*.qmd"
    type: grid
    fields: [image, title, description] 
    sort: "date"
    image-height: 150px
  - id: inferential_statistics
    contents: "posts/inferential_statistics/*.qmd"
    type: grid
    fields: [image, title, description] 
  - id: ml_fundamentals
    contents: "posts/ml_fundamentals/*.qmd"
    type: grid
    fields: [image, title, description] 
  - id: supervised_learning
    contents: "posts/supervised_learning/*.qmd"
    type: grid
    fields: [image, title, description] 
  - id: unsupervised_learning
    contents: "posts/unsupervised_learning/*.qmd"
    type: grid
    fields: [image, title, description] 
  - id: deep_learning
    contents: "posts/deep_learning/*.qmd"
    type: grid
    fields: [image, title, description] 
  - id: model_deploy
    contents: "posts/model_deploy/*.qmd"
    type: grid
    fields: [image, title, description] 
  - id: hands_on
    contents: "posts/hands_on/*.qmd"
    type: grid
    fields: [image, title, description] 
---

## Foundation in Mathematics and Statistics

:::{#foundations}
:::

## Inferential Statistics

:::{#inferential_statistics}
:::

    -   Sampling Techniques (random sampling, stratified sampling)

    -   Confidence Intervals

    -   Hypothesis Testing (null hypothesis, p-values, Type I and Type II errors)

    -   Confidence Intervals vs. Hypothesis Testing

    -   Power Analysis

## Machine Learning Fundamentals

:::{#ml_fundamentals}
:::

    -   Introduction to Machine Learning

    -   Supervised Learning vs. Unsupervised Learning vs. Reinforcement Learning

    -   Model Evaluation and Selection (cross-validation, bias-variance tradeoff)

    -   Feature Engineering (feature selection, feature scaling)

    -   Model Evaluation Metrics (accuracy, precision, recall, F1 score, ROC curve, AUC)

## Supervised Learning Algorithms

:::{#supervised_learning}
:::

    -   Linear Regression

    -   Logistic Regression

    -   Decision Trees

    -   Random Forests

    -   Support Vector Machines (SVM)

    -   k-Nearest Neighbors (k-NN)

    -   Naive Bayes

## Unsupervised Learning Algorithms

:::{#unsupervised_learning}
:::

    -   K-Means Clustering

    -   Hierarchical Clustering

    -   Principal Component Analysis (PCA)

    -   t-Distributed Stochastic Neighbor Embedding (t-SNE)

    -   Association Rule Learning (Apriori Algorithm)

## Deep Learning

:::{#deep_learning}
:::

    -   Neural Networks Basics

    -   Feedforward Neural Networks

    -   Convolutional Neural Networks (CNNs)

    -   Recurrent Neural Networks (RNNs)

    -   Long Short-Term Memory (LSTM) Networks

    -   Gated Recurrent Units (GRUs)

## Model Deployment and Production

:::{#model_deploy}
:::

    -   Model Deployment Techniques (RESTful APIs, Docker containers)

    -   Model Monitoring and Maintenance

    -   Ethical Considerations in Machine Learning

## Practical Projects and Hands-On Experience

:::{#hands_on}
:::

    -   Work on real-world datasets and projects to apply what you've learned.

    -   Kaggle competitions, online courses with practical exercises, and personal projects can all be valuable.

